"""Add rate.

Revision ID: 31014ba76381
Revises: de891a31e53e
Create Date: 2022-03-29 20:45:25.971834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31014ba76381'
down_revision = 'de891a31e53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('rate', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_model', 'rate')
    # ### end Alembic commands ###
